name: Docker Image CI

on:
  push:
    branches: [ "fix-docker-support" ]
  pull_request:
    branches: [ "fix-docker-support" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push wprfreact image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: your-dockerhub-username/wprfreact:$(date +%s)

    - name: Build and push wprfapi image
      uses: docker/build-push-action@v2
      with:
        context: ../wprfAPI
        file: ../wprfAPI/Dockerfile
        push: true
        tags: your-dockerhub-username/wprfapi:$(date +%s)
