name: Docker Image CI

on:
  push:
    branches: [ "fix-docker-support" ]
  pull_request:
    branches: [ "fix-docker-support" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2 
      with:
        username: friedrice69
        password: dckr_pat_M73wEbvQA9emTXx0y_7i3riXg1E
        # password: ${{ secrets.wpr }}

    - name: Build and push wprfreact image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: friedrice69/wprfreact:${{ github.run_id }}

    - name: Build and push wprfapi image
      uses: docker/build-push-action@v2
      with:
        context: ../wprfAPI
        file: ../wprfAPI/Dockerfile
        push: true
        tags: friedrice69/wprfapi:${{ github.run_id }}
